### ISSUE TITLE
Missing or outdated version of limb.so.6

### ISSUE THREAD

**Issue by Marfien** [Octops/agones-event-broadcaster#21]
I got an error while deploying the broadcaster to my k8s cluster:
`./broadcaster: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./broadcaster)`

**Comment by Marfien** [comment]
Sorry, didn't used the latest tag. Should be updated in the install yaml

**Comment by danieloliveira079** [comment]
Hello @Marfien this is a valid issue and I am pushing the fix now. I am upgrading the project to use Go 1.17 and Debian Bookworm. That fixed the problem.

I am pushing the manifests now and the docker image to Docker Hub. Please use the image tag 0.3.5.

For reference: https://github.com/Octops/agones-event-broadcaster/pull/22

**Comment by danieloliveira079** [comment]
The docker image tagged latest is very old. I am also pushing latest to be the same as 0.3.5.

Let me know if you are still facing issues. If you pulled latest older than NOW please run docker pull again.

Preferable use the tag 0.3.5.
